fuente:
  driver: postgresql
  host: localhost
  port: 5432
  user: postgres
  password: 
  db: rapidos_y_furiosos

bodega:
  driver: postgresql
  host: localhost
  port: 5432
  user: postgres
  password: 
  db: rapidos_y_furiosos_bodega